# Site Settings
title: iDoTrick | Damith's portfolio and technology blog
email: idotrick.public@gmail.com
description: Damith is a Full Stack Java Developer, a tech enthusiast. iDoTrick is his portfolio and technology blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-120968098-1"

# User Settings
authorname: Damith
author_description: Full Stack Java Developer | Tech Enthusiast
username: iDoTrick
user_description: Damith is a Full Stack Java Developer, a tech enthusiast.
disqus_username: idotrick

# Social Media
# Remove the item if you don't need it
github_username: github_username
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Portfolio
    url: /module/portfolio/
  - title: Skills
    url: /tags/
  - title: Blog
    url: /module/blog/
  - title: Contact
    url: /module/contact/

category_urls:
  ifs: http://www.ifsworld.com
  dxc: http://www.dxc.com
  integro: http://www.integrosys.com

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
